version: '3.6'

services:
  
  database:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin 
    ports:
      - 5432:5432
    volumes:
      - /tmp/postgresql_data/:/var/lib/postgresql/data